name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Checkstyle and Unit Tests
      run: ./gradlew clean check 
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GH_TOKEN }}
        min-coverage-overall: 60
        min-coverage-changed-files: 70
        update-comment: true
        pass-emoji: ':green_circle:'
        fail-emoji: ':red_circle:'
    - name: Fail PR if overall coverage is less than 70%
      if: ${{ steps.jacoco.outputs.coverage-overall < 70.0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Overall coverage is less than 70%!')
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
